spring:
  application:
    name: Lblog-spring-cloud-service-admin

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

  jackson:
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true

server:
  port: 8762



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #通过这个url找到服务端eureka server的地址，然后注册到eureka服务器


reply:
  avatar: /images/avatars/2.jpg

